services:
  todo-frontend:
    image: todo-frontend-dev
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=api/
    volumes:
      - ./todo-frontend:/usr/src/app
    container_name: todo-frontend-dev
    depends_on:
      - todo-backend
    
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes: 
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      #- ./todo-backend/mongo_data:/data/db
      
  redis:
    image: redis
    ports:
      - 6379:6379
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - ./todo-backend/redis_data:/data

  todo-backend:
    image: todo-backend-dev
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    volumes:
      - ./todo-backend/:/usr/src/app
    container_name: todo-backend-dev
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
    depends_on:
      - mongo
      - redis
  
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:  
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - todo-frontend

volumes:
  mongo_data:
